// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/shared/database/prisma/schema.prisma",
  migrations: {
    path: "src/shared/database/prisma/migrations",
  },
  datasource: {
    url: process.env["NEXT_PRISMA_SUPABASE_DB_URL"],
    shadowDatabaseUrl: process.env["NEXT_PRISMA_DIRECT_URL"]
  },
});
